// Tienda Angular/src/app/Inicio/CarritoDeCompras/CarritoDeCompras.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../../data.service';

@Component({
  selector: 'app-CarritoDeCompras',

  templateUrl: './CarritoDeCompras.component.html',

  styleUrls: ['./CarritoDeCompras.component.css']
})


export class ComponenteCarritoDeCompras implements OnInit {
  shoppingCartJSON:any;
  constructor(private dataService: DataService) {

    this.shoppingCartJSON = this.dataService.getShoppingCart();
  }

  ngOnInit() {
  }

  updateProductsStock(){
    this.dataService.updateProductsStock(this.shoppingCartJSON);
  }

}

<div>
  <h2>Carrito de compras</h2>
</div>


<div class="row" *ngIf="shoppingCartJSON.length > 0">

  <div class="col-sm-6">

    <ul class="list-group shoppingCartListDiv">

      <li class="list-group-item" *ngFor="let shoppingCart of shoppingCartJSON">
          <div class="productDetails">

            <img class="card-img-top" [src]="shoppingCart.product.img" alt="Card image cap" width="10%" height="10%">

            <div class="productText">
              <p>{{shoppingCart.product.nombre}}</p>
              <p><strong>Unidades: </strong>{{shoppingCart.quantity}}</p>
            </div>

          </div>
          <p><strong>Subtotal: </strong>$ {{shoppingCart.subtotal}}</p>
      </li>

    </ul>

  </div>


  <div class="col-sm-6">
    <h2>Total: $ {{dataService.shoppingCartTotal}}</h2>
    <a type="button" class="btn btn-default" routerLink="/Inicio/CatalogoDeProductos">Cancelar</a>
    <a type="button" class="btn btn-default" (click)="updateProductsStock()">Pagar</a>
  </div>
  
</div>

// Tienda React/components/carritoDeCompras.jsx
import React from 'react';


const badgeColor = {
  backgroundColor : 'red'
}


const productDetails = {
  display: 'flex'
}


const productText = {
  marginLeft: '2%'
}


const body = {
  backgroundColor: 'white',
  padding: '2%'
}


class CarritoDeCompras extends React.Component{
    constructor(){
     super();
    }

    render(){
        return(
            <div style={body} className="row">
              <div className="col-sm-12">
                <div className="col-sm-12 col-md-6 text-left">
                  <h1>Carrito de Compras</h1>
                </div>
              </div>
              <div className="col-sm-6">
                <ul className="list-group">
                  {this.props.CarritoDeCompras.map((item, i) =>
                    <li className="list-group-item" key={i}>
                        <div style={productDetails}>
                          <img className="card-img-top" src={item.producto.img} alt="" width="10%" height="10%"/>
                          <div style={productText}>
                            <p>{item.producto.nombre}</p>
                            <p><strong>Unidades: </strong>{item.quantity}</p>
                          </div>
                        </div>
                        <p><strong>Subtotal: </strong>$ {item.subTotal}</p>
                    </li>
                  )}
                </ul>
              </div>




              <div className="col-sm-6">
                <h2>Total: $ {this.props.CarritoDeComprasTotal}</h2>
                <a type="button" className="btn btn-default" onClick={this.props.verLaListaDelCatalogo.bind(this)}>Cancelar</a>
                <a type="button" className="btn btn-default" onClick={this.props.revisarCarritoDeCompras.bind(this)}>Pagar</a>
              </div>
            </div>
            );
        }
      }

export default CarritoDeCompras;
